### ISSUE TITLE
Eye tracking from recorded videos?

### ISSUE THREAD

**Issue by dpaniukov** [esdalmaijer/PyGaze#112]
Hello,
Is it possible to use pygaze to track whether a person (an infant) looks at the screen (under the camera), using a recording from the camera? The data are already collected, so I cannot do anything else with it. 
Thanks for your suggestions!

**Comment by esdalmaijer** [comment]
Hi Dmitrii,

Eye tracking from existing videos is beyond the scope of PyGaze, but would potentially be possible with sister-project [webcam-eyetracker](https://github.com/esdalmaijer/webcam-eyetracker). This offers a [generic eye tracking class](https://github.com/esdalmaijer/webcam-eyetracker/blob/master/PyOpenCV/pygazetracker/generic.py) that can be inherited by different input classes. You could write one for video input based on the [webcam input class](https://github.com/esdalmaijer/webcam-eyetracker/blob/master/PyOpenCV/pygazetracker/webcam.py) (which also uses OpenCV VideoCapture, so essentially you just need to swap out the webcam feed for a video file name.

Please note that mapping eye orientation to gaze position will be hard without a calibration, and that matching video feed and on-screen information might be tough without markers in the video.

Good luck!
Edwin

**Comment by dpaniukov** [comment]
Thanks a bunch for your comments! I will check out the references :)
