### ISSUE TITLE
Tobii Calibration Fail

### ISSUE THREAD

**Issue by annieaitken123** [esdalmaijer/PyGaze#114]
Hi,

I'm running a tobii eye tracking experiment with infants which means that calibration often fails the first try. When calibration fails, I do not get a chance to redo calibration. Instead, the experiment starts right away and eye tracking is not recorded. Is there any way to remedy this?

Thanks,
Annie

**Comment by scattenlaeufer** [comment]
The `calibrate()` function returns whether it was successful or not. Just run a loop around it and check whether it worked or not. If it didn't, just let `calibrate()` run again.
