### ISSUE TITLE
Tobii Pro SDK - Pygaze TSV File

### ISSUE THREAD

**Issue by hcuve** [esdalmaijer/PyGaze#123]
![2](https://user-images.githubusercontent.com/41246596/51922892-d5050300-23e1-11e9-9df4-35ce98f5e5c9.PNG)

Dear Devs @grebdems @pedrotari7 

I am using a Tobii tx300 with opensesame and I am experiencing an issue with the way the TSV file in open sesame is logging information.

While the time stamps and the rest of the raw data is logged to the tsv file, in some cases this is logged in the wrong columns (see photo), when logging a message (e.g. start trial or stop trial).
I should point that this appears to be random, and for that reason it makes it hard to just correct it by writing a R script or something of sorts. It kinda forces you to double check and correct for this manually, by readjusting the time-stamp to it's column, the message as well as some of the gaze values (Gazepoints, validity and pupil).
@esdalmaijer do you have any idea of what may be causing this?

Just for reference, this is how a similar message should be logged
![3](https://user-images.githubusercontent.com/41246596/51923092-290fe780-23e2-11e9-8edc-55cb60fb6d05.PNG)
and this should match these column labels
![labels](https://user-images.githubusercontent.com/41246596/51923126-37f69a00-23e2-11e9-9729-0db84f5daf19.PNG)

Thank you,

Cheers!
Helio

**Comment by hcuve** [comment]
Hi all,

sorry to bring this up again, but I was wondering if you have any idea of what might be causing this issue above?? @grebdems @pedrotari7 @esdalmaijer

**Comment by grebdems** [comment]
Hi, sorry for the (very) late answer.
Me and @pedrotari7 only work part time with this project and it's sometimes hard to find the time to do all the things you wished you could...
I did manage to reproduce this a while after you posted the issue, and I'm fairly confident it's just needs a lock around the log writing call. However, I haven't had time to verify that that works, so I don't want to push any changes. 
I think I'll have time to check this in a couple of weeks. Sorry for the slow response.

**Comment by hcuve** [comment]
Thank you @grebdems and @pedrotari7 totally understand!

If it's just adding or fixing some lines of code, I am happy to try and implement and see whether it solves it? If you can share the solution?

In any case, thanks again for looking into it.

Best wishes
Hélio

**Comment by grebdems** [comment]
@esdalmaijer Have you had time to look at my PR to fix this issue?
@hcuve did you test to pull the PR and use it by any chance?

**Comment by esdalmaijer** [comment]
Just merged it! (Thanks for the reminder!)

**Comment by hcuve** [comment]
Hi @esdalmaijer  and @grebdems  so sorry I thought I had already reported back. Yes I did try the fix and it does solve the issue. Ran a number of people on different machines and it seems to work fine now! Thank you!

Cheers
Helio

**Comment by haleyk** [comment]
hello! thank you so much for the fix for this issue. I was wondering if you have any idea if the lines that were miswritten are one above/below where the log should be (ie, it is safe to assume that the log is as close as possible to its actual log time as can be expected)? If this is the case and other people in the future have data with this issue, I can share my python script to fix the problem in already collected data
