### ISSUE TITLE
Eyetracker calibrate sets wrong area size

### ISSUE THREAD

**Issue by EmmaDelhaye** [esdalmaijer/PyGaze#135]
Hi,

I'm new at using `PyGaze` and I'm trying to use a SMI RED 500 eyetracker.
The communication between my task and the eyetracker works fine but it looks like it always sets the calibration area size to `(0, 0)`.

Here are the commands sent to iView:
```shell
ET_CSZ 0 0
ET_CPA 2 1
ET_CPA 3 1
ET_CSZ 0 0
```
But the resolution set for the eyetracker is `(1680, 1050)`.
I tried to send these commands manually but `ET_CAL 9` is never sent...

Do you have any idea on how to fix this? I can't find any way to provide parameters to `Eyetracker.calibrate()`.

Best,
Emma

**Comment by esdalmaijer** [comment]
Hi Emma,

According to the iViewX documentation, the command `ET_CSZ` sets the calibration area size. You're passing `0` as the width and `0` as the height in your command `ET_CSZ 0 0`. Shouldn't that be `ET_CSZ 1680 1050`?

Cheers,
Edwin

**Comment by EmmaDelhaye** [comment]
Hi,

Thank you for your answer! Yes I tried that solution but it didn't work; OpenSesame systematically sent the ET_CSZ 0 0 command to iView X.
Good news is that I found the solution to the problem by changing my DVI connecting cable to a VGA connecting cable to the Stimulus-display screen. Now everything works fine.

Thanks again for taking the time to read me & answer!
Best,
Emma

**Comment by esdalmaijer** [comment]
To be honest, I'm still unsure what's actually causing the (0,0) resolution to be set... Glad that you found a solution, though! :)
