### ISSUE TITLE
Inescapable frozen grey screen on eyetracking examples

### ISSUE THREAD

**Issue by qsimeon** [esdalmaijer/PyGaze#148]
Hi,

I am using macOS Catalina and I tried running you simple tracker experiment example. It just created a full screen grey screen that did nothing and was impossible to exit out of. My only option was to har shut down my mac? What do I need to get this to work on Mac, I have installed all the dependencies and I assumed that this would work with just my laptop webcam?

**Comment by esdalmaijer** [comment]
Unfortunately, that's the wrong assumption.

For a toy example of webcam eye tracking, see: https://github.com/esdalmaijer/webcam-eyetracker
