### ISSUE TITLE
time.clock depreciated

### ISSUE THREAD

**Issue by raykyn** [esdalmaijer/PyGaze#155]
Hi, thanks for this very useful software!
When trying the example scripts today, I encountered an error and found the problem.
Because time.clock() is depreciated since Python Version 3.3, scripts using libtime doesn't work in newer versions.

I'll try to fix it myself and issue a pull request when I find the time.

**Comment by esdalmaijer** [comment]
Thanks for pointing this out!

**Comment by esdalmaijer** [comment]
Fixed with commit [2deecc8dd87b6c5a469da1ea0e515cbe292ea6f1](https://github.com/esdalmaijer/PyGaze/commit/2deecc8dd87b6c5a469da1ea0e515cbe292ea6f1)!
