### ISSUE TITLE
FileNotFoundError: Could not find module 'iViewXAPI.dll' (or one of its dependencies). Try using the full path with constructor syntax.

### ISSUE THREAD

**Issue by johnbone25** [esdalmaijer/PyGaze#157]
How can i use the eye tracking?
I get this error by running "simple_tracker_experiment.py"

![image](https://user-images.githubusercontent.com/82903709/115956558-b842d180-a4fd-11eb-97a9-c9af9cca3bdf.png)

**Comment by esdalmaijer** [comment]
Change the `TRACKERTYPE` away from `smi` if you're not currently using an SMI tracker. If you are, then make sure you have iView installed.
