### ISSUE TITLE
Could not find module 'iViewXAPI.dll' (or one of its dependencies). Try using the full path with constructor syntax.

### ISSUE THREAD

**Issue by Shaukat456** [esdalmaijer/PyGaze#162]
How can I manually install iViewAPI.dill since the pygaze doesn't seem to work without it? 

![eror](https://user-images.githubusercontent.com/65353819/143887892-deac2280-de7e-4208-816e-10db128730a3.PNG)

**Comment by esdalmaijer** [comment]
That DLL is only necessary if you're trying to use an eye-tracker from SensoMotoric Instruments (SMI). If you're not, don't set `TRACKERTYPE = "smi"`. If you are, then you should have the DLL from SMI itself, as it's a proprietary library. You might have to do some digging around to find it on your computer; it should be somewhere in the SMI SDK files.
