### ISSUE TITLE
Eye image not shown in Eyelink calibration screen

### ISSUE THREAD

**Issue by dschreij** [esdalmaijer/PyGaze#23]
pygaze commit afef6d913357ca6b8e996747ee1f1b54dbce4e45
Windows 7; Opensesame 2.8.3
tested on EyeLink CL (1000) and Eyelink 2000

When you are in the calibration menu of the EyeLink and select to see the eye image by pressing the <enter> key, you are presented with a black screen.The calibration and such works, so the eyelink can detect and record the eye and thus there seems to be no problem with the connection. This did work with previous versions of pygaze, so did something go wrong upstream maybe?

**Comment by dev-jam** [comment]
I would like to reopen this bug. On Debian Buster and Bullseye I have the same problem. 
It worked in the past on Debian Buster, with an older pygaze / opensesame combination. 
The problem does not occur with Windows 10 with the latest opensesame / pygaze / python3 combination. 
I don't get any errors. I tried some older combinations with python2 and python3 on both Buster and Bullseye without any luck.
Calibration and validation work.

Current setup is:

Debian Bullseye amd64

OpenSesame 3.3.7b1
python 3.9.1
expyriment 0.10
pygaze 0.7.2a1
pylink 1.11 for python3.9, send by sr-research
Eyelink 1000+
