### ISSUE TITLE
wait_for_fixation_start() for Tobii tracker doesn't return the right time

### ISSUE THREAD

**Issue by scattenlaeufer** [esdalmaijer/PyGaze#45]
If I understand the code correctly, `wait_for_fixation_start()` for Tobii tracker doesn't return the time the fixation started, but the time the fixation was detected. Those times have a difference of at least `self.fixtimetresh`.

Since I am not sure whether this is a wanted behaviour, I didn't just fix it and create a pull request, but reported this as an issue to check whether it is really an issue.

**Comment by esdalmaijer** [comment]
Sorry, I must have forgot about this! Thanks for the pull request, it looks fine. And it makes sense to do it like this. The initial behaviour was intended to return the time of detection, but you're right: that might not necessarily be what you'd expect.

**Comment by esdalmaijer** [comment]
TODO: standardise this behaviour across all modules. [EyeLink](https://github.com/esdalmaijer/PyGaze/blob/master/pygaze/_eyetracker/libeyelink.py#L887), [EyeTribe](https://github.com/esdalmaijer/PyGaze/blob/master/pygaze/_eyetracker/libeyetribe.py#L955), and [SMI](https://github.com/esdalmaijer/PyGaze/blob/master/pygaze/_eyetracker/libsmi.py#L1059).
