### ISSUE TITLE
Installer issue: installed in python3.4 package folder and not python 2.7.  from Cogsci PPA

### ISSUE THREAD

**Issue by wkruijne** [esdalmaijer/PyGaze#54]
Hey there,

Sorry, I had no idea where else to report this...

Today I have tried to update my pygaze because the plugin version I was using did no longer work in Opensame  3.0 . However, both running `sudo apt-get install python-pygaze`, OR running `sudo ./setup.py install` manually did not properly update my package. 

After some digging around I found out that both were installing the package in my ` /usr/local/lib/python3.4/dist-packages/pygaze/`, thereby making it invisible to python 2.7 (and thereby invisible to opensesame and others). I could fix it by running `python setup.py install` instead, but perhaps the installer could/should be updated to assert both python dist's have the proper version running?

Thanks,
W

**Comment by smathot** [comment]
Hi Wouter,

Are you running a beta of Ubuntu 16.04 by any chance? I understood that they are moving toward Python 3 as default, so I can imagine this kind of confusion arising.

Cheers,
Sebastiaan

**Comment by wkruijne** [comment]
Nope, I'm actually very delayed with my updates and  still on 15.04 -- default sym-link to `python' is still 2.7 (which I guess is why I could fix it by running `python setup.py install`)

**Comment by wkruijne** [comment]
I just spotted that setup.py starts with:
```
#!/usr/bin/env python3
```
...that would  probably be the culprit then, wouldn't it?
