### ISSUE TITLE
libinput.py needs updating for newer PsychoPy versions

### ISSUE THREAD

**Issue by peircej** [esdalmaijer/PyGaze#59]
An error message about weakref has come up on the psychopy users list that would be best fixed in PyGaze libinput.py

https://groups.google.com/forum/#!topic/psychopy-users/SllmUo3egNs

PsychoPy's storage of open windows switched to using weak references a while ago to avoid circular references that were preventing proper garbage collection. A simple fix is suggested (but untested) in the link above.

**Comment by peircej** [comment]
Oh, this is probably a duplicate of #48
I think the fix suggested above will fix that too

**Comment by esdalmaijer** [comment]
Hi Jon,

Thanks for the info! We ran into the issue earlier, and fixed it by referring directly to the active window. See the PsychoPyMouse class, [line 59](https://github.com/esdalmaijer/PyGaze/blob/master/pygaze/_mouse/psychopymouse.py#L59).

The code you cited in the linked Google Group page is from an older version of PyGaze. (That's my bad for not advertising the newer version enough!)

Cheers,
Edwin
