### ISSUE TITLE
Psychopy visual.Circle fillcolor changes background color of screen object

### ISSUE THREAD

**Issue by hannehuygelier** [esdalmaijer/PyGaze#60]
Dear dr Dalmaijer,

Thank you for developing this software package! 

While learning to work with PyGaze I noticed that setting fillcolor of visual.Circle changes the background color to the same color as the fillcolor of the circle object. I worked around it, but thought that it would be best to notify you. (I am using your WinPython-PyGaze-0.4 module.)

Regards,
Hanne Huygelier

**Comment by esdalmaijer** [comment]
Hi Hanne,

Thanks for noticing! Could you provide a minimal example (short script) in which this occurs, please? It would help us pinpoint and solve the issue :)

I'm sure @peircej would also be interested in this. (Sounds like a PsychoPy thing?)

Cheers,
Edwin

**Comment by peircej** [comment]
Yes indeed. A minimal example for us to test with would be very useful
thanks
