### ISSUE TITLE
GP3 support

### ISSUE THREAD

**Issue by horvatha** [esdalmaijer/PyGaze#63]
I would be happy if Gazepoint GP3 would be supported by PyGaze/OpenSesame.
## Our story

I have written a mail to the psychologist colleague of mine about PyGaze. He was were very enthusiastic. He bring the GP3 device to our university from his work place and we started to experimenting with the device with the vendor's software. But we have a limited support for the analysis software of GP3. OGAMA was recommended by someone, but **I like Python very much** and I prefer Python to C# and I do not want to use Windows for the analysis.
## Can I help you?

I would happily give PyGaze a try, but as I have read on forum, it does not support it. I would be hard to get it work with PyGaze/OpenSesame? If it is not hard, perhaps I would help you. (I have written some Python programs as you can see on Github, I am not a beginner.) But _I need help_:
- I do not know where to start.
- I know GP3 has an interface API based on TCP/IP, but I do not know, how to reach it on OS-es other than Windows (I use Ubuntu and Debian).
- I have not investigated the structure of PyGaze yet and I have not used is yet, because I have no other device to try it.
- I have found a MATLAB code, that could be the starting point of the code: https://github.com/mperez4/gazepoint_toolkit

**Comment by esdalmaijer** [comment]
Thanks for offering your help! To answer your questions:

Background
------------
PyGaze's design is very modular. There is a generic [EyeTracker class](https://github.com/esdalmaijer/PyGaze/blob/master/pygaze/eyetracker.py#L28) that morphs into a class that is dedicated to a specific brand/type of eye trackers.

These dedicated classes can be found in the [_eyetracker module](https://github.com/esdalmaijer/PyGaze/tree/master/pygaze/_eyetracker), and work in the same way: They inherit the [BaseEyeTracker class](https://github.com/esdalmaijer/PyGaze/blob/master/pygaze/_eyetracker/baseeyetracker.py#L52), and redefine the basic functions (see below) to work with a specific API.


GP3 Specifics
-------------

Unfortunately, I'm completely unfamiliar with the device, and do not have access to one. You mention the API is TCP/IP based, which is not unlike other existing implementations. For example, the [EyeTribeTracker class](https://github.com/esdalmaijer/PyGaze/blob/master/pygaze/_eyetracker/libeyetribe.py#L69) offers support through a socket connection with a local server. The [SMItracker](https://github.com/esdalmaijer/PyGaze/blob/master/pygaze/_eyetracker/libsmi.py#L123) class does something similar, but regulated via a (propriety) DLL from SensoMotoric Instruments that handles communications with a server (this can be local, but also on a different PC).

On the other side, there are the [libeyelink](https://github.com/esdalmaijer/PyGaze/blob/master/pygaze/_eyetracker/libeyelink.py#L74) and the [TobiiTracker](https://github.com/esdalmaijer/PyGaze/blob/master/pygaze/_eyetracker/libtobii.py#L102) classes that are built on top of highly specific APIs (provided by SR Research and Tobii, respectively).

I would highly recommend to have a look at the implementation for EyeTribe and SMI trackers. If you have any specific questions, for example on what each method is expected to do, I'd be happy to help!


Basic functions
---------------
These are the functions you probably want to define, considering they form the basic functionality for using an eye tracker. For documentation on each, see the [BaseEyeTracker class](https://github.com/esdalmaijer/PyGaze/blob/master/pygaze/_eyetracker/baseeyetracker.py#L52). For an example on how to implement them, see the [EyeTribeTracker class](https://github.com/esdalmaijer/PyGaze/blob/master/pygaze/_eyetracker/libeyetribe.py#L69).

* calibrate
* close
* connected
* drift_correction
* log
* pupil_size
* sample
* start_recording
* stop_recording
* wait_for_*

**Comment by esdalmaijer** [comment]
We've implemented this ourselves, so closing this issue.
