### ISSUE TITLE
EyeTribe get_frame() error

### ISSUE THREAD

**Issue by hannehuygelier** [esdalmaijer/PyGaze#68]
While using the EyeTribe eyetracker, an error occurs (see error message below). This error seems to occur while a pause screen is presented to the user (before presenting this screen I stop recording with the eyetracker). If I print out the content of response, the dictionary does not contain u'frame' after the values, but it contains u'calibresults'. Is it wrong to stop the recording during pauze screens in the experiment? (This error also occurred while trying to run the simple_tracker_experiment example after one of the first trials).

Exception in thread samplestreamer:
Traceback (most recent call last):
  File "C:\Python27\lib\threading.py", line 810, in __bootstrap_inner
    self.run()
  File "C:\Python27\lib\threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "C:\Python27\lib\site-packages\pygaze\_eyetracker\pytribe.py", line 238, in _stream_samples
    sample = self._tracker.get_frame()
  File "C:\Python27\lib\site-packages\pygaze\_eyetracker\pytribe.py", line 851, in get_frame
    return {	'timestamp':	response['values']['frame']['timestamp'],
KeyError: 'frame'

**Comment by esdalmaijer** [comment]
This is an interesting one; I'm not sure how a 'calibresults' results ended up there. Would you mind elaborating on what you're trying to do exactly, preferably in a short code snippet? (I.e. where does it go wrong? Are you, for example, trying to get a sample while the tracker is not recording?)

Also, minor point, would you mind sharing what version of PyGaze you are using? Is it the latest commit? (A commit number would be great :) )

**Comment by esdalmaijer** [comment]
Should be solved with [this commit](https://github.com/esdalmaijer/PyGaze/commit/7828afaea7e8fdeb155c96538fefb57ef2d2e933).
