### ISSUE TITLE
Update 'stable version' links on the project website

### ISSUE THREAD

**Issue by cherepaha** [esdalmaijer/PyGaze#81]
On http://www.pygaze.org/downloads/ the 'stable version' downloads (both normal and portable) still point to v0.4, which is quite old, evidently. As pointed by @esdalmaijer in comments to #48, the links need to be updated to v0.5

**Comment by esdalmaijer** [comment]
Good point! Will update the website ASAP (and the docs, when I have the time).

**Comment by esdalmaijer** [comment]
The links were already updated to version 0.5, but I forgot to close this. Incidentally, I just updated the links on the website to version 0.6.0. Woop!
