### ISSUE TITLE
import sys in libwebcam.py

### ISSUE THREAD

**Issue by camelia-c** [esdalmaijer/PyGaze#82]
Hello,

I just want to point out that I needed to add:

import sys

in  PyGaze/additional_libraries/libwebcam.py

on Ubuntu 16.04.1 LTS, with Python 2.7

Best regards,
Camelia

**Comment by esdalmaijer** [comment]
Thanks for flagging that up!

**Comment by toshikurauchi** [comment]
Maybe this issue should be closed? @lparth fixed it on #147

**Comment by camelia-c** [comment]
Yes, I agree.
