### ISSUE TITLE
Is PyGaze input data from Eye-tribe only?

### ISSUE THREAD

**Issue by b524524778** [esdalmaijer/PyGaze#86]
Is PyGaze input data from Eye-tribe? although I have Rawdata from MobileEye but I don't know how to feed data to PyGaze..

is data only from Eye-tribe or EyeLink II?

**Comment by esdalmaijer** [comment]
Hi,

You might be confused with PyGaze Analyser, which can take data from SMI, EyeLink, and EyeTribe.

PyGaze does not take any input data; it's a library to code experiments in.

Cheers,
Edwin
