### ISSUE TITLE
simple_tracker_experiment.py not working

### ISSUE THREAD

**Issue by muhammadkhan** [esdalmaijer/PyGaze#87]
I'm trying to run simple_tracker_experiment.py provided on the website but I'm always getting this error:

`Traceback (most recent call last):
  File "simple_tracker_experiment.py", line 7, in <module>
    from pygaze import libscreen
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/pygaze/libscreen.py", line 22, in <module>
    from screen import Screen
ImportError: cannot import name 'Screen'`

I'm pretty sure I've installed all dependencies, even the Python 3 versions. Why am I still getting this?

**Comment by joji7** [comment]
I guess we are supposed to use python2.7, not python3. I just solved that problem using python2.7

**Comment by jclevesque** [comment]
Doesn't seem to work on Mac OSX.

**Comment by Di-Sagli** [comment]
I use python3.6 and I solved it using this command 
sudo apt-get install python3-tk

**Comment by aribeller** [comment]
Just want to clarify a point. I'm taking from @esdalmaijer's endorsement of @srinivasj7's comment that pygaze is implemented only for python2 and not python3?
