### ISSUE TITLE
Is it right to use it on Windows?

### ISSUE THREAD

**Issue by RunxueBao** [esdalmaijer/PyGaze#88]
Dear Edwin, 

I am trying to run PyGaze on windows 10. I download WinPython-PyGaze-0.5.1 and unzip it first. And then I install pygame-1.9.1.win32-py2.7 and StandalonePsychoPy-1.82.01-win32. As I understand it,
it is enough to run the experiments. Next I run WinPython Command Prompt.exe and run examples downloaded from your website. Some examples give error messages. 

I have some questions. Firstly, is PyGaze can run well to realize eye-tracking without any other software or hardware? Secondly, is what I do and understand above right to run PyGaze? Thirdly, is that PyGaze invokes the camera of my laptop and does not need any other hardware?  I am trying my best to understand the excellent work you have done but I really have some problems. Please reply me back and answer my question.

Thank you! 
Runxue Bao

**Comment by esdalmaijer** [comment]
Hi,

As the website says, PyGaze is developed to make it easier to work with existing eye trackers. So you will need external hardware to run it. You might be confused with my [webcam eye-tracker project](https://github.com/esdalmaijer/webcam-eyetracker).

As for your other question: The WinPython version should work as a standalone on Windows without any further installation of Python libraries (except for hardware-specific software, if your eye-tracker or other device requires this). So you needn't install PyGame, and definitely not the Standalone version of PsychoPy (which, as its name implies, is a standalone programme - that's not the same thing as the PsychoPy Python library that we use).

Good luck!
