### ISSUE TITLE
eyetribe firmware update tool

### ISSUE THREAD

**Issue by sjobeek** [esdalmaijer/PyGaze#90]
Hello, I hate to pollute your issues with this question, but I've run into issues getting my pytribe device running and believe i need to update my device firmware since its an early unit. 

Does anyone on this team happen to have a copy of the firmware update tool they could send me, or know where i could find it?

**Comment by esdalmaijer** [comment]
Apparently everything can now be found on GitHub:

https://github.com/EyeTribe/sdk-installers/releases
https://github.com/EyeTribe/documentation
